---
# playbook for test image 
- hosts: localhost
  vars:
    ip1: '192.168.1.31/24'  # for nataddr test
  tasks:
    - name: Get hostname
      command: hostname
      register: rs_hostname

    - name: Print the result
      debug: var=rs_hostname.stdout

    - name: Test SSH
      command: ssh 127.0.0.1 hostname
      register: rs_ssh_hostname
      ignore_errors: yes

    - name: Print the result of SSH
      debug: var=rs_ssh_hostname.stdout

    - name: netaddr test - set fact
      set_fact:
        ip1_net: "{{ ip1|ansible.netcommon.ipv4('network') }}"
    
    - name: netaddr netwokr output
      debug: var=ip1_net

    - name: Test SSH with Password
      block:
        - name: Add host for password test
          add_host:
            name: test-password-host
            ansible_host: 127.0.0.1
            ansible_user: test-user
            ansible_password: test-pass

        - name: Test ssh with password
          block:
            - name: Run command to check ssh. The connection is supposed to be rejected.
              command: /bin/true
              ignore_unreachable: yes
              register: do_password_ssh
              failed_when:
                - '"failed" in do_password_ssh'
                - '"sshpass" in do_password_ssh.msg'

            - name: Test following 
              debug: var=ansible_host
          delegate_facts: true
          delegate_to: test-password-host

      tags: ssh_pass_test






