---
# usage: docker-compose run --rm ansible ansible-playbook pb.test.yml 
version: "3.6"
services:
  ansible:
    image: kimcharli/ansible-ubuntu
    container_name: ansible
    volumes:
      - ./playbook:/playbook
      - ~/.ssh:/root/.ssh

